#------------------------------------------------------------------------------------------------------------------------
#                                                BulletPro PHISHING KIT Detection
#------------------------------------------------------------------------------------------------------------------------
# The files detected by tags in this list have been connected to BulletPro Phishing-as-a-Service / shop, which targets 
# a number of consumer and corporate brands. Detections should be immediately investigated.
#------------------------------------------------------------------------------------------------------------------------
apidatacss.com
apiserverdata1.com
baller.top
bomohsmtp.com
Bulletproftink.com
bulletproftlink.com
dasmtp.com
datacenter01.us
earthsmtp.com
f1smtp.com
Failedghostsmtp.com
Failedsendapidata.com
Faileduebpicture.cc
feesmtp.com
foxsmtp.com
ghostsmtp.com
gpxsmtp.com
gurl101.services
hostprivate.us
josmtp.com
jupitersmt.com
laptopdata.xyz
link101.bid
linuxsmtp.com
mainsmtp.com
mexsmtp.com
migration101.us
moneysmtp.com
panelsmtp.com
plutosmto.com
prvtsmtp.com
racksmtp.com
rosmtp.com
rxasmtp.com
sendapidata.com
ses-smtp.com
smtpro101.com
smtptemp.site
thegreenmy87.com
trasactionsmtp.com
valvadi101.com
vitme.bid
voksmtp.com
webpicture.cc
winsmtp.com
function sendemail_using_sendgrid(
function mg(a, o, t) {
$TheBoss
finish-unv2.php
finish-unv22.php
/email-list/
anthraxbcg
#------------------------------------------------------------------------------------------------------------------------
