#------------------------------------------------------------------------------------------------------------------------
# The URLs in this tag file have been observed in phishing kits, or victimized by phishing kits. Detections should be
# treated as suspicious and confirmed manually. If you're not expecting to see a given URL used on your website or service
# that should be seen as a red flag. When detections happen within this tag file and other tag files, 
# the weighted view should be seen as cause for investigation.
#------------------------------------------------------------------------------------------------------------------------
#                                                1-and-1 Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
1and1.com
ionos.com
#------------------------------------------------------------------------------------------------------------------------
#                                                ABSA Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
absa.co.za
#------------------------------------------------------------------------------------------------------------------------
#                                                Alibaba Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
1688.com
alibaba.com
alibabagroup.com
alicdn.com
aliexpress.com
alimama.com
alitrip.com
aliunicorn.com
aliyun.com
autonavi.com
dingtalk.com
intl.alipay.com
laiwang.com
taobao.com
tmall.com
ttpod.com
umeng.com
us.my.alibaba.com
xiami.com
yunos.com
#------------------------------------------------------------------------------------------------------------------------
#                                                Amazon Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
amazon.com
amazon.de
amazon.co.jp
amazon.fr
#------------------------------------------------------------------------------------------------------------------------
#                                                Apple Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
apple.com
appleid.apple.com
icloud.com
iforgot.apple.com
#------------------------------------------------------------------------------------------------------------------------
#                                                AT&T Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
att.com
att.net
attplans.com
currently.att.yahoo.com
#------------------------------------------------------------------------------------------------------------------------
#                                                Banking
#------------------------------------------------------------------------------------------------------------------------
akessiefbehrporle.com
alaskausa.org
bancogalicia.com.ar
bankia.es
bankofamerica.com
banqueentreprise.bnpparibas
banquepopulaire.fr
bcpzonasegurabeta.viabcp.com
bdo.com.ph
caisse-epargne.fr
caixabank.es
cic.fr
citi.com
connect.secure.wellsfargo.com
credicard.com.br
credit-agricole.fr
credit-card-information.elliottback.com
creditmutuel.fr
discover.com
eldni.com
equabank.cz
fibank.bg
group.bnpparibas
hellobank.fr
ibx.key.co
internet-banking.dbs.com.sg
itau24horas.ml
itau.com.br
labanquepostale.fr
leboncoin.fr
login.regions.com
mabanque.bnpparibas
mabanqueprivee.bnpparibas
moneyissues.ng
nedbank.co.za
nwolb.com
online.adp.com
onlinebanking.firstcaribbeanbank.com
onlinebanking.pnc.com
openknowledge.worldbank.org
portal.pnb.com.ph
regions.com
santander.com.br
secure.alpha.gr
squareup.com
visaprepaidprocessing.com
western-security.net
wetransfer.com
www.kh.hu
#------------------------------------------------------------------------------------------------------------------------
#                                                Credit Monitoring
#------------------------------------------------------------------------------------------------------------------------
creditkarma.ca
creditkarma.com
econsumer.equifax.ca
equifax.ca
equifax.com
equifaxcreditwatch.ca
members.transunion.ca
transunion.ca
transunion.com
#------------------------------------------------------------------------------------------------------------------------
#                                                Bell Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
sympatico.ca
bell.net
#------------------------------------------------------------------------------------------------------------------------
#                                                Blockchain Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
coinbase.com
commerce.coinbase.com
prime.coinbase.com
pro.coinbase.com
developers.coinbase.com
safemoon.net
#------------------------------------------------------------------------------------------------------------------------
#                                                BT Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
btbusiness.custhelp.com
bt.custhelp.com
bt.co.uk
btmail.bt.com
home.bt.com
btinternet.com
#------------------------------------------------------------------------------------------------------------------------
#                                                Costco Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
costco.ca
costco.com
costco.co.uk
costcophotocenter.com
costcotravel.ca
costcotravel.co
#------------------------------------------------------------------------------------------------------------------------
#                                                DHL Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
dhl.com
dhl.de
#------------------------------------------------------------------------------------------------------------------------
#                                                Document Scams
#------------------------------------------------------------------------------------------------------------------------
app.lawofficeneal.online
app.nealrose-lawoffices.online
files.lawoffice-nealroseberg.online
files.lawofficesof-nealrose.online
secured.lawfirmnearl.online
secured.rosellawassocciates.online
secure.lawoffices-of-neal.online
secure.nealrose-lawofficerecords.online
#------------------------------------------------------------------------------------------------------------------------
#                                                Education
#------------------------------------------------------------------------------------------------------------------------
osu.edu
#------------------------------------------------------------------------------------------------------------------------
#                                                Government
#------------------------------------------------------------------------------------------------------------------------
benefits.ides.illinois.gov
gov.uk
health.ny.gov
idot.illinois.gov
labor.maryland.gov
labor.ny.gov
mass.gov
my.ny.gov
pua.benefits.uc.pa.gov
recruiting.jcf.gov.jm
ui-cares-act.mass.gov
wisconsin.gov
#------------------------------------------------------------------------------------------------------------------------
#                                                Spectrum Phishing
#------------------------------------------------------------------------------------------------------------------------
spectrum.net
watch.spectrum.net
webmail.roadrunner.com
webmail.spectrum.net
#------------------------------------------------------------------------------------------------------------------------
#                                                ISPs and Tech Services
#------------------------------------------------------------------------------------------------------------------------
accounts.login.idm.telekom.com
ad.aruba.it
akamaihd.net
akamaized.net
app-id=com.vzw.hss.myverizon
auth.centurylink.net
bitrix24.com
csolve.net
docusign.com
docusign.net
ftcdn.net
godaddy.com
kyivstar.net
login.frontier.com
login.t-online.de
mega.bw
mobile.de
nexmo.com
onetrust.com
onlinehome.de
optimum.net
optusnet.com.au
orange.fr
rackspace.com
sailpoint.com
seanet.com
siteserve.jp
socket.net
static.licdn.com
swisscom.ch
tatic-exp1.licdn.com
tawk.to
telekom.de
tiqcdn.com
tlh.ro
westnet.com.au
wowway.net
wvtc.com
www.nutopia.com.au
#------------------------------------------------------------------------------------------------------------------------
#                                                Kit Functions
#------------------------------------------------------------------------------------------------------------------------
2no.co
api.ipapi.com
api.userstack.com
bincodes.com
binlist.net
bins.pro
bins.ribbon.co
cdnii.e-i.com
ci4.googleusercontent.com
ci5.googleusercontent.com
curl.haxx.se
cutt.ly
dancevida.com
dclic-resolver.e-i.com
extreme-ip-lookup.com
i.ibb.co
ip2geo.com
ipapi.co
ip-api.com
ip-api.org
ip-geo.ru
ipinfodb.com
ipinfo.io
iplocationtools.com
ipqualityscore.com
iptool.xyz
killbot.org
likemyphp.com
lookup.binlist.net
me2mekrf.com
postimg.org
proxy.mind-media.com
remotemysql.com
safebrowsing.googleapis.com
smtp.mailtrap.io
trublcon.com
upcloud.host
xooimage.com
yimg.com
#------------------------------------------------------------------------------------------------------------------------
#                                                Kit Markets and Advertising
#------------------------------------------------------------------------------------------------------------------------
7812w.pl
7jyewu.cn
a2ztoolz.com
anonymousfox.com
buyshellsites.com
cdnsw.com
fudscript.com
ghc.ru
indoxploit.blogspot.co.id
kuzuluy.app
l34kc0de.today
Market0day.com
marketx.bz
orvx.pw
priv8tool.club
rst.void.ru
s3curity.tn
sh33nz0.com
shem3a.com
soundbible.com
theseotools.net
top4top.com
top4top.io
top4top.net
topscript.xyz
tpa.uma.ac.id
ubhteam.org
webtoolhub.com
withoutshadow.org
wos-linuxers.blogspot.com
www.a-l-e-x-u-s.ru
#------------------------------------------------------------------------------------------------------------------------
#                                                Mail
#------------------------------------------------------------------------------------------------------------------------
banglamail.com
email.t-online.de
login.t-online.de
gallery.mailchimp.com
groupmail.io
mailfence.com
mail.herkules-polska.pl
mail.mpi-cbg.de
mail.ru
mail.sina.com.cn
msgsafe.io
portail.free.fr
rackspacemail.com
verizon.yahoo.com
wakwak.com
webmail.canvas.ne.jp
webmail.earthlink.net
webmail.shaw.ca
webtop.webmail.optimum.net
yandex.com
yandex.ru
ymail.com
#------------------------------------------------------------------------------------------------------------------------
#                                                Media
#------------------------------------------------------------------------------------------------------------------------
2m.ma
comrise.ru
#------------------------------------------------------------------------------------------------------------------------
#                                                Microsoft Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
live.com
microsoftonline.com
msauth.net
msftauth.net
logincdn.msauth.net
#------------------------------------------------------------------------------------------------------------------------
#                                                PayPal Phishing Kits
#------------------------------------------------------------------------------------------------------------------------
localheartz.club
paypal.co.jp
paypal.com
paypal.de
paypal.fr
snsv-crew.id
#------------------------------------------------------------------------------------------------------------------------
#                                                Postal Scams
#------------------------------------------------------------------------------------------------------------------------
bancoposta.poste.it
correos.cl
fedex.com
postandparcel.info
postepay.poste.it
postoffice.co.uk
royalclass.com.ar
usps.com
#------------------------------------------------------------------------------------------------------------------------
#                                                Social Media
#------------------------------------------------------------------------------------------------------------------------
126.com
163.com
163.goooo
daum.net
match.com
naver.com
ourtime.com
sina.com
static.xx.fbcdn.net
wa.me
#------------------------------------------------------------------------------------------------------------------------
#                                                Spam Links Discovered in Kits
#------------------------------------------------------------------------------------------------------------------------
clearmen.lienquan.garena.vn
1thang5.lienquan.garena.vn
#------------------------------------------------------------------------------------------------------------------------
#                                                Quiz / Survey Scams
#------------------------------------------------------------------------------------------------------------------------
fsuxeua2yzwtgh.bar
opgarwfw.hf28x.cn
vxlwdyo.cn
uzyivzf.cn
#------------------------------------------------------------------------------------------------------------------------
#                                                Miscellaneous
#------------------------------------------------------------------------------------------------------------------------
34.127.100.133
acs4.3dsecure.no
api.bestfriendstore.net
bluehouselondon.com
boyxd.com
d2papa.com
etraxer.com
firb.br
forwallpaper.com
ikhbaljb.com
maersk.com
newlife.com
o54eavgyktxh5wts.onion
oijhgbfvergyt4res.appspot.com
okinawa-grandmer.com
oneprosec.com
sgp.fas.org
shopget24.com
spKINGS.com
szatr.com
tmd-sa.co.za
tourdeindia.asia
tsbdumbs.com
vdsafvdfgfdhdgfh.cz
#------------------------------------------------------------------------------------------------------------------------
