#------------------------------------------------------------------------------------------------------------------------
# The URLs in this tag file have been observed in phishing kits, or victimized by phishing kits. Detections should be
# treated as suspicious and confirmed manually. When detections happen within this tag file and other tag files, 
# the weighted view should be seen as cause for investigation.
#------------------------------------------------------------------------------------------------------------------------
#                                                Banking
53.com
akessiefbehrporle.com
alaskausa.org
anz.com.au
anz.co.nz
anz.com
bancogalicia.com.ar
bankia.es
banqueentreprise.bnpparibas
banquepopulaire.fr
bcpzonasegurabeta.viabcp.com
bpergroup.net
bper.it
bdo.com.ph
caisse-epargne.fr
caixabank.es
cic.fr
citi.com
commercebank.com
connect.secure.wellsfargo.com
cra-arc.gc.ca
credicard.com.br
credit-agricole.fr
credit-card-information.elliottback.com
creditmutuel.fr
ebank.dibpak.com
eldni.com
equabank.cz
fibank.bg
group.bnpparibas
hellobank.fr
ibx.key.co
ing.nl
internet-banking.dbs.com.sg
itau24horas.ml
itau.com.br
labanquepostale.fr
leboncoin.fr
login.regions.com
mabanque.bnpparibas
mabanqueprivee.bnpparibas
moneyissues.ng
mtb.com
navyfederal.org
nedbank.co.za
nwolb.com
online.adp.com
onlinebanking.firstcaribbeanbank.com
onlinebanking.pnc.com
openknowledge.worldbank.org
portal.pnb.com.ph
parsian-bank.ir
relaxbanking.it
regions.com
santander.com.br
secure.alpha.gr
sella.it
standardbank.com.na
squareup.com
tescobank.com
.ubs.com
visaprepaidprocessing.com
western-security.net
wetransfer.com
www13.bmo.com
www.kh.hu
#                                                Credit Monitoring
creditkarma.ca
creditkarma.com
econsumer.equifax.ca
equifax.ca
equifax.com
equifaxcreditwatch.ca
members.transunion.ca
transunion.ca
transunion.com
#                                                Costco Phishing Kits
costco.ca
costco.com
costco.co.uk
costcophotocenter.com
costcotravel.ca
costcotravel.co
#                                                Document Scams
app.lawofficeneal.online
app.nealrose-lawoffices.online
files.lawoffice-nealroseberg.online
files.lawofficesof-nealrose.online
secured.lawfirmnearl.online
secured.rosellawassocciates.online
secure.lawoffices-of-neal.online
secure.nealrose-lawofficerecords.online
#                                                Education
adfs.lu.se
correo.bl.fcen.uba.ar
ident.univ-amu.fr
luservicedesk.service-now.com
mail.bl.fcen.uba.ar
mail.ethz.ch
nmail.unileoben.ac.at
osu.edu
webmail.lu.se
webmail.unvime.edu.ar
wmail.hines.hokudai.ac.jp
#                                                Government
acq.osd.mil
benefits.ides.illinois.gov
cdph.ca.gov
edd.ca.gov
gov.uk
health.mo.gov
health.ny.gov
idot.illinois.gov
labor.maryland.gov
labor.ny.gov
mass.gov
my.ny.gov
nj.gov
pua.benefits.uc.pa.gov
recruiting.jcf.gov.jm
ui-cares-act.mass.gov
wisconsin.gov
#                                                ISPs and Tech Services
accounts.login.idm.telekom.com
ad.aruba.it
akamaihd.net
akamaized.net
app-id=com.vzw.hss.myverizon
bitrix24.com
csolve.net
deloitte.com
deloitteresources.com
ftcdn.net
iinet.net.au
kyivstar.net
login.frontier.com
login.t-online.de
mega.bw
mobile.de
myhughesnet.com
nexmo.com
onetrust.com
onlinehome.de
optusnet.com.au
orange.fr
rackspace.com
rackspacemail.com
sailpoint.com
seanet.com
siteserve.jp
socket.net
spotify.com
spark.co.nz
static.licdn.com
swisscom.ch
t-online.de
tatic-exp1.licdn.com
tawk.to
telekom.de
tiqcdn.com
tlh.ro
weebly.com
westnet.com.au
wowway.net
wvtc.com
www.nutopia.com.au
#                                                Kit Functions
2no.co
api.ipapi.com
apilayer.net
api.nichicodex.xyz
api.npoint.io
api.userstack.com
bincodes.com
binlist.net
bins.pro
bins.ribbon.co
cdnii.e-i.com
ci4.googleusercontent.com
ci5.googleusercontent.com
cookiebot.com
countryflags.io
curl.haxx.se
cutt.ly
dancevida.com
dclic-resolver.e-i.com
dox2x.com
evil-payment.com
extreme-ip-lookup.com
i.ibb.co
ip2geo.com
ipapi.co
ip-api.com
ip-api.org
ip-geo.ru
ipinfodb.com
ipinfo.io
iplocationtools.com
ipqualityscore.com
iptool.xyz
ipwhois.app
killbot.org
likemyphp.com
lookup.binlist.net
me2mekrf.com
mx-api.com
nullrefer.com
postimg.org
proxy.mind-media.com
remotemysql.com
safebrowsing.googleapis.com
site4now.net
smtp.mailtrap.io
trublcon.com
upcloud.host
xooimage.com
yimg.com
#                                                Kit Markets and Advertising
7812w.pl
7jyewu.cn
a2ztoolz.com
anonymousfox.com
buyshellsites.com
cdnsw.com
fudscript.com
ghc.ru
indoxploit.blogspot.co.id
jerux.to
kuzuluy.app
l34kc0de.today
leafmailer.pw
Market0day.com
marketx.bz
orvx.pw
priv8tool.club
rst.void.ru
s3curity.tn
sh33nz0.com
shem3a.com
soundbible.com
theseotools.net
top4top.com
top4top.io
top4top.net
topscript.xyz
tpa.uma.ac.id
ubhteam.org
webtoolhub.com
withoutshadow.org
wos-linuxers.blogspot.com
www.a-l-e-x-u-s.ru
#                                                Mail
antispam.spg-llc.com
arsmtp.com
banglamail.com
emailsrvr.com
email.t-online.de
gallery.mailchimp.com
gandi.net
groupmail.io
inbound-2.mimecast.com
itwconnect.com
login.t-online.de
mailanyone.net
mailfence.com
mail.herkules-polska.pl
mail.mpi-cbg.de
mail.ru
mail.sina.com.cn
msgsafe.io
mtaroutes.com
mtsmail.ca
mxthunder.co
parsons-peebles.com
portail.free.fr
ppe-hosted.com
pphosted.com
secureserver.net
skynet.be
verizon.yahoo.com
wakwak.com
webmail.canvas.ne.jp
webmail.sda.it
webmail.shaw.ca
yandex.com
yandex.ru
ymail.com
#                                                Media
2m.ma
comrise.ru
#                                                Postal Scams
bancoposta.poste.it
correos.cl
epg.ae
fedex.com
postandparcel.info
postepay.poste.it
postoffice.co.uk
royalclass.com.ar
royalmail.com
#                                                Retail
shopifycdn.com
shopify.com
etsy.com
etsystatic.com
#                                                Social Media
126.com
163.com
163.goooo
daum.net
match.com
naver.com
ourtime.com
sina.com
static.xx.fbcdn.net
wa.me
#                                                Spam Links Discovered in Kits
clearmen.lienquan.garena.vn
1thang5.lienquan.garena.vn
#                                                Quiz / Survey Scams
fsuxeua2yzwtgh.bar
opgarwfw.hf28x.cn
vxlwdyo.cn
uzyivzf.cn
#                                                Miscellaneous
34.127.100.133
acs4.3dsecure.no
api.bestfriendstore.net
bluehouselondon.com
boyxd.com
centraletermo.ro
clubonerealtors.com
d2papa.com
etraxer.com
firb.br
forwallpaper.com
hkelectric.com
ikhbaljb.com
ims.connectlar.org
intuitcdn.net
intuit.com
jeann8.com
maersk.com
newlife.com
o54eavgyktxh5wts.onion
oijhgbfvergyt4res.appspot.com
okinawa-grandmer.com
oneprosec.com
sgp.fas.org
shopget24.com
spKINGS.com
stewart.com
surveygizmo.com
szatr.com
tmd-sa.co.za
tourdeindia.asia
tsbdumbs.com
vdsafvdfgfdhdgfh.cz
zixcorp.com
#------------------------------------------------------------------------------------------------------------------------
